### ISSUE TITLE
Errors when trying to get data from ORU

### ISSUE THREAD

**Issue by ElGranPepo** [bvlaicu/coned#7]
Thank you for putting this together, really excited to use it!

I followed the instructions and the info from @kunalkhosla to get my UUID and my meter and can see my data in my browser when using the URL  https://oru.opower.com/ei/edge/apis/cws-real-time-ami-v1/cws/oru/accounts/<YOUR_ACCOUNT_UUID>/meters/<YOUR_METER_NUMBER>/usage
in this  format: {"startTime":"2021-11-03T17:45:00-04:00","endTime":"2021-11-03T18:00:00-04:00","value":0.2770}
but when i try to run the addon i get a bunch of errors as below:

Params:
EMAIL = jxyz@gmail.com
PASSWORD = **********orq!$
MFA_TYPE = TOTP
MFA_SECRET = **********frgts
ACCOUNT_UUID = ac624eyy-b0xx-11yy-bfxx-xxxyyyyxxxxy
METER_NUMBER = 7010xxxx
SITE = oru
MQTT_HOST = hassio.local
MQTT_USER = mqtt
MQTT_PASS = **********1$$
Starting endless loop..
[1104/173349.266603:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
DevTools listening on ws://127.0.0.1:33807/devtools/browser/fcb17349-06e5-45ca-88a4-bcd251558355
[1104/173349.272310:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is disabled
[1104/173349.643896:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
DevTools listening on ws://127.0.0.1:46823/devtools/browser/64676853-4b5a-4495-b704-a0b403f4a1ab
[1104/173349.652351:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is disabled
[1104/173351.591201:WARNING:spdy_session.cc(3431)] Received HEADERS for invalid stream 5
[1104/173351.911196:INFO:CONSOLE(11)] "Uncaught TypeError: Cannot read property 'split' of undefined", source: about:srcdoc (11)
[1104/173352.033401:INFO:CONSOLE(11)] "Uncaught TypeError: Cannot read property 'split' of undefined", source: about:srcdoc (11)
[1104/173353.164731:INFO:CONSOLE(1)] "'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.", source: https://siteintercept.qualtrics.com/dxjsmodule/CoreModule.js?Q_CLIENTVERSION=1.63.1&Q_CLIENTTYPE=web&Q_BRANDID=coned (1)
[1104/173353.395074:INFO:CONSOLE(1)] "'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.", source: https://siteintercept.qualtrics.com/dxjsmodule/CoreModule.js?Q_CLIENTVERSION=1.63.1&Q_CLIENTTYPE=web&Q_BRANDID=coned (1)
[1104/173435.365173:INFO:CONSOLE(1)] "'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.", source: https://siteintercept.qualtrics.com/dxjsmodule/CoreModule.js?Q_CLIENTVERSION=1.63.1&Q_CLIENTTYPE=web&Q_BRANDID=coned (1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 99, in last_read
    for read in jsonResponse['reads']:
KeyError: 'reads'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    startTime, endTime, value, uom = asyncio.get_event_loop().run_until_complete(meter.last_read())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 114, in last_read
    raise MeterError("Error requesting meter data")
coned.meter.MeterError: Error requesting meter data
Task exception was never retrieved
future: <Task finished coro=<Meter.browse() done, defined at /usr/local/lib/python3.7/dist-packages/coned/meter.py:116> exception=NetworkError('Protocol error Page.navigate: Target closed.')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 162, in browse
    await api_page.goto(api_url)
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/page.py", line 877, in goto
    result = await self._navigate(url, referrer)
  File "/usr/local/lib/python3.7/dist-packages/pyppeteer/page.py", line 892, in _navigate
    'Page.navigate', {'url': url, 'referrer': referrer})
pyppeteer.errors.NetworkError: Protocol error Page.navigate: Target closed.
Task was destroyed but it is pending!
task: <Task pending coro=<NavigatorWatcher._createTimeoutPromise.<locals>._timeout_func() running at /usr/local/lib/python3.7/dist-packages/pyppeteer/navigator_watcher.py:96> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f815489b528>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<wait() running at /usr/lib/python3.7/asyncio/tasks.py:363> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f815489bdf8>()]> cb=[NavigatorWatcher.__init__.<locals>.<lambda>() at /usr/local/lib/python3.7/dist-packages/pyppeteer/navigator_watcher.py:54]>

im in rockland not sure if that makes a difference.

**Comment by ElGranPepo** [comment]
now getting this:

Starting endless loop..
[1104/180053.841353:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
DevTools listening on ws://127.0.0.1:34617/devtools/browser/beaf65d4-ae0f-40e1-8407-32c670289ffd
[1104/180053.848029:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is disabled
[1104/180054.216928:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
DevTools listening on ws://127.0.0.1:39769/devtools/browser/2f3d3551-a6b9-4aff-9a12-8a8bbdbbf2ac
[1104/180054.224779:ERROR:gpu_init.cc(426)] Passthrough is not supported, GL is disabled
[1104/180055.742084:INFO:CONSOLE(40)] "Unrecognized feature: 'attribution-reporting'.", source: https://www.googletagmanager.com/gtm.js?id=GTM-PK7RZ5 (40)
[1104/180055.743650:INFO:CONSOLE(40)] "Unrecognized feature: 'conversion-measurement'.", source: https://www.googletagmanager.com/gtm.js?id=GTM-PK7RZ5 (40)
[1104/180056.309452:INFO:CONSOLE(40)] "Unrecognized feature: 'attribution-reporting'.", source: https://www.googletagmanager.com/gtm.js?id=GTM-PK7RZ5 (40)
[1104/180056.311403:INFO:CONSOLE(40)] "Unrecognized feature: 'conversion-measurement'.", source: https://www.googletagmanager.com/gtm.js?id=GTM-PK7RZ5 (40)
[1104/180057.700302:INFO:CONSOLE(1)] "'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.", source: https://siteintercept.qualtrics.com/dxjsmodule/CoreModule.js?Q_CLIENTVERSION=1.63.1&Q_CLIENTTYPE=web&Q_BRANDID=coned (1)
[1104/180057.730555:INFO:CONSOLE(1)] "'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.", source: https://siteintercept.qualtrics.com/dxjsmodule/CoreModule.js?Q_CLIENTVERSION=1.63.1&Q_CLIENTTYPE=web&Q_BRANDID=coned (1)
[1104/180139.685972:INFO:CONSOLE(40)] "Unrecognized feature: 'attribution-reporting'.", source: https://www.googletagmanager.com/gtm.js?id=GTM-PK7RZ5 (40)
[1104/180139.687112:INFO:CONSOLE(40)] "Unrecognized feature: 'conversion-measurement'.", source: https://www.googletagmanager.com/gtm.js?id=GTM-PK7RZ5 (40)
[1104/180140.489896:INFO:CONSOLE(1)] "'webkitRequestAnimationFrame' is vendor-specific. Please use the standard 'requestAnimationFrame' instead.", source: https://siteintercept.qualtrics.com/dxjsmodule/CoreModule.js?Q_CLIENTVERSION=1.63.1&Q_CLIENTTYPE=web&Q_BRANDID=coned (1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 99, in last_read
    for read in jsonResponse['reads']:
KeyError: 'reads'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "run.py", line 18, in <module>
    startTime, endTime, value, uom = asyncio.get_event_loop().run_until_complete(meter.last_read())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/coned/meter.py", line 114, in last_read
    raise MeterError("Error requesting meter data")
coned.meter.MeterError: Error requesting meter data

**Comment by dubnom** [comment]
I'm getting the same errors.  Did anyone figure out what is causing these?
